#!/usr/bin/env python3
"""Rewrite a `wrangler d1 export` dump into an order D1 can actually load.

The export interleaves each table's CREATE with its INSERTs, in no particular
order, and leans on `PRAGMA defer_foreign_keys=TRUE` at the top of the file to
survive the resulting forward references. That pragma only holds inside one
transaction, and wrangler splits a large file into batches — so on the way back
in, the rows of a child table can arrive before the parent table exists:

    CREATE TABLE user_avatars (user_id TEXT ... REFERENCES users(id) ...);
    INSERT INTO "user_avatars" ...   <- fails: no such table: main.users
    CREATE TABLE "users" (...);

Locally that goes unnoticed: sqlite3 has foreign keys OFF by default, so the
same file loads clean. D1 has them ON.

This reads the dump into a scratch database (where it does load), then writes it
back out as: every CREATE TABLE first, then the rows table by table in
dependency order, then indexes and triggers. Parents before children, so the
constraints hold at every point.

    normalise-d1-export.py <input.sql> <output.sql> [--skip-rows=t1,t2]

--skip-rows emits a table's CREATE but none of its rows, so the table arrives
empty rather than missing. refresh-dev-db.sh uses it for the base64 image
tables (#359): member photos have no business on a preview, and carrying
megabytes across only to DELETE them on arrival is a slow way to reach the same
place. Skipping a table with children would strand foreign keys, so anything
listed here must be a leaf.
"""
import re
import sqlite3
import sys
import tempfile
from pathlib import Path


def literal(v):
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, bytes):
        return "X'" + v.hex() + "'"
    return "'" + str(v).replace("'", "''") + "'"


def topological(tables, deps):
    """Parents first. Cycles keep their input order rather than being dropped."""
    ordered, seen = [], set()

    def visit(t, stack):
        if t in seen or t in stack:
            return
        stack.add(t)
        for parent in deps.get(t, ()):
            if parent in tables:
                visit(parent, stack)
        stack.discard(t)
        seen.add(t)
        ordered.append(t)

    for t in tables:
        visit(t, set())
    return ordered


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    flags = [a for a in sys.argv[1:] if a.startswith("--")]
    if len(args) != 2:
        sys.exit(__doc__)
    src, dest = Path(args[0]), Path(args[1])

    skip_rows = set()
    for f in flags:
        if f.startswith("--skip-rows="):
            skip_rows = {t.strip() for t in f[len("--skip-rows=") :].split(",") if t.strip()}
        else:
            sys.exit(f"unknown option: {f}\n{__doc__}")

    with tempfile.TemporaryDirectory() as tmp:
        db = sqlite3.connect(Path(tmp) / "scratch.db")
        # Foreign keys stay OFF here on purpose: this is the one context where
        # the dump's own ordering is tolerated, which is what lets us read it.
        db.executescript(src.read_text())

        rows = db.execute(
            "SELECT type, name, sql FROM sqlite_master "
            "WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' AND name NOT LIKE '_cf_%'"
        ).fetchall()

        tables = [n for t, n, _ in rows if t == "table"]
        ddl = {n: s for t, n, s in rows if t == "table"}
        rest = [s for t, _, s in rows if t != "table"]

        deps = {}
        for t in tables:
            parents = {
                r[2] for r in db.execute(f'PRAGMA foreign_key_list("{t}")').fetchall()
            }
            deps[t] = parents - {t}  # self-references order themselves

        order = topological(tables, deps)

        missing = skip_rows - set(tables)
        if missing:
            sys.exit(f"--skip-rows names tables not in the dump: {', '.join(sorted(missing))}")
        # Emptying a parent orphans every child row pointing at it, and the load
        # runs with foreign keys ON — so it would fail here rather than quietly
        # produce a broken preview. Say so now, with the offending pair named.
        stranded = [
            (child, parent)
            for child in tables
            if child not in skip_rows
            for parent in deps.get(child, ())
            if parent in skip_rows
        ]
        if stranded:
            pairs = ", ".join(f"{c} -> {p}" for c, p in sorted(stranded))
            sys.exit(f"--skip-rows would strand foreign keys: {pairs}")

        out = [
            "-- Generated by scripts/normalise-d1-export.py — do not edit.",
            "-- Tables and rows are emitted parents-first so foreign keys hold",
            "-- at every point of the load. See the script for why.",
            "PRAGMA defer_foreign_keys=TRUE;",
        ]
        for t in order:
            out.append(ddl[t] + ";")
        for t in order:
            if t in skip_rows:
                out.append(f"-- rows for {t} skipped (--skip-rows)")
                continue
            cols = [r[1] for r in db.execute(f'PRAGMA table_info("{t}")').fetchall()]
            collist = ",".join(f'"{c}"' for c in cols)
            for row in db.execute(f'SELECT * FROM "{t}"'):
                values = ",".join(literal(v) for v in row)
                out.append(f'INSERT INTO "{t}" ({collist}) VALUES({values});')
        for s in rest:
            out.append(s + ";")

        dest.write_text("\n".join(out) + "\n")

    # Report on stderr: stdout stays free for callers that want to pipe.
    skipped = f", rows skipped for {len(skip_rows)}" if skip_rows else ""
    print(f"normalised {len(tables)} tables{skipped} -> {dest}", file=sys.stderr)


if __name__ == "__main__":
    main()
