#!/usr/bin/env python3
"""Rewrite a `wrangler d1 export` dump into an order D1 can actually load.

The export interleaves each table's CREATE with its INSERTs, in no particular
order, and leans on `PRAGMA defer_foreign_keys=TRUE` at the top of the file to
survive the resulting forward references. That pragma only holds inside one
transaction, and wrangler splits a large file into batches — so on the way back
in, the rows of a child table can arrive before the parent table exists:

    CREATE TABLE user_avatars (user_id TEXT ... REFERENCES users(id) ...);
    INSERT INTO "user_avatars" ...   <- fails: no such table: main.users
    CREATE TABLE "users" (...);

Locally that goes unnoticed: sqlite3 has foreign keys OFF by default, so the
same file loads clean. D1 has them ON.

This reads the dump into a scratch database (where it does load), then writes it
back out as: every CREATE TABLE first, then the rows table by table in
dependency order, then indexes and triggers. Parents before children, so the
constraints hold at every point.

    normalise-d1-export.py <input.sql> <output.sql>
"""
import re
import sqlite3
import sys
import tempfile
from pathlib import Path


def literal(v):
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, bytes):
        return "X'" + v.hex() + "'"
    return "'" + str(v).replace("'", "''") + "'"


def topological(tables, deps):
    """Parents first. Cycles keep their input order rather than being dropped."""
    ordered, seen = [], set()

    def visit(t, stack):
        if t in seen or t in stack:
            return
        stack.add(t)
        for parent in deps.get(t, ()):
            if parent in tables:
                visit(parent, stack)
        stack.discard(t)
        seen.add(t)
        ordered.append(t)

    for t in tables:
        visit(t, set())
    return ordered


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    src, dest = Path(sys.argv[1]), Path(sys.argv[2])

    with tempfile.TemporaryDirectory() as tmp:
        db = sqlite3.connect(Path(tmp) / "scratch.db")
        # Foreign keys stay OFF here on purpose: this is the one context where
        # the dump's own ordering is tolerated, which is what lets us read it.
        db.executescript(src.read_text())

        rows = db.execute(
            "SELECT type, name, sql FROM sqlite_master "
            "WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' AND name NOT LIKE '_cf_%'"
        ).fetchall()

        tables = [n for t, n, _ in rows if t == "table"]
        ddl = {n: s for t, n, s in rows if t == "table"}
        rest = [s for t, _, s in rows if t != "table"]

        deps = {}
        for t in tables:
            parents = {
                r[2] for r in db.execute(f'PRAGMA foreign_key_list("{t}")').fetchall()
            }
            deps[t] = parents - {t}  # self-references order themselves

        order = topological(tables, deps)

        out = [
            "-- Generated by scripts/normalise-d1-export.py — do not edit.",
            "-- Tables and rows are emitted parents-first so foreign keys hold",
            "-- at every point of the load. See the script for why.",
            "PRAGMA defer_foreign_keys=TRUE;",
        ]
        for t in order:
            out.append(ddl[t] + ";")
        for t in order:
            cols = [r[1] for r in db.execute(f'PRAGMA table_info("{t}")').fetchall()]
            collist = ",".join(f'"{c}"' for c in cols)
            for row in db.execute(f'SELECT * FROM "{t}"'):
                values = ",".join(literal(v) for v in row)
                out.append(f'INSERT INTO "{t}" ({collist}) VALUES({values});')
        for s in rest:
            out.append(s + ";")

        dest.write_text("\n".join(out) + "\n")

    # Report on stderr: stdout stays free for callers that want to pipe.
    print(f"normalised {len(tables)} tables -> {dest}", file=sys.stderr)


if __name__ == "__main__":
    main()
